[workspace]
members = [
    "crates/core",
    "crates/markdownify",
    "crates/rasteroid",
]
resolver = "3"

# The profile that 'dist' will build with
[profile.dist]
inherits = "release"
codegen-units = 1
lto = "fat"

[patch.crates-io]
markdownify = { path = "crates/markdownify" }
